name: sparepart
description: A new Flutter application.

# Versi aplikasi
version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons untuk ikon gaya iOS
  cupertino_icons: ^1.0.5 # Update ke versi terbaru Cupertino Icons

  # Tambahkan dependensi lain yang Anda perlukan di sini

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1 # Update ke versi terbaru flutter_lints untuk linting terbaik

# Bagian khusus untuk Flutter
flutter:

  # Gunakan Material Design
  uses-material-design: true

  # Menambahkan aset gambar ke aplikasi
  assets:
    - images/

  # Menambahkan font khusus ke aplikasi
  fonts:
    - family: Staatliches
      fonts:
        - asset: fonts/Staatliches-Regular.ttf
    - family: Oxygen
      fonts:
        - asset: fonts/Oxygen-Regular.ttf
